### ISSUE TITLE
`synvert -r rails/upgrade_5_0_to_5_1` failed

### ISSUE THREAD

**Issue by znz** [xinminlabs/synvert-snippets#20]
How to reproduce:

```
% cat a.rb
h = {}
v = h['k']
% synvert -r rails/upgrade_5_0_to_5_1
===== rails/upgrade_5_0_to_5_1 started =====
.../lib/ruby/gems/2.3.0/gems/synvert-core-0.14.0/lib/synvert/core/node_ext.rb:91:in `message': message is not handled for  (Synvert::Core::MethodNotSupported)
file: /tmp/x/a.rb
line: 2
source: h
node: s(:lvar, :h)
	from (eval):21:in `block (4 levels) in load_rewriters'
	from .../lib/ruby/gems/2.3.0/gems/synvert-core-0.14.0/lib/synvert/core/rewriter/scope/within_scope.rb:30:in `instance_eval'
	from .../lib/ruby/gems/2.3.0/gems/synvert-core-0.14.0/lib/synvert/core/rewriter/scope/within_scope.rb:30:in `block (3 levels) in process'
	from .../lib/ruby/gems/2.3.0/gems/synvert-core-0.14.0/lib/synvert/core/rewriter/instance.rb:140:in `process_with_node'
	from .../lib/ruby/gems/2.3.0/gems/synvert-core-0.14.0/lib/synvert/core/rewriter/scope/within_scope.rb:29:in `block (2 levels) in process'
	from .../lib/ruby/gems/2.3.0/gems/synvert-core-0.14.0/lib/synvert/core/rewriter/scope/within_scope.rb:28:in `each'
	from .../lib/ruby/gems/2.3.0/gems/synvert-core-0.14.0/lib/synvert/core/rewriter/scope/within_scope.rb:28:in `block in process'
	from .../lib/ruby/gems/2.3.0/gems/synvert-core-0.14.0/lib/synvert/core/rewriter/instance.rb:140:in `process_with_node'
	from .../lib/ruby/gems/2.3.0/gems/synvert-core-0.14.0/lib/synvert/core/rewriter/scope/within_scope.rb:22:in `process'
	from .../lib/ruby/gems/2.3.0/gems/synvert-core-0.14.0/lib/synvert/core/rewriter/instance.rb:165:in `within_node'
	from (eval):20:in `block (3 levels) in load_rewriters'
	from .../lib/ruby/gems/2.3.0/gems/synvert-core-0.14.0/lib/synvert/core/rewriter/instance.rb:101:in `instance_eval'
	from .../lib/ruby/gems/2.3.0/gems/synvert-core-0.14.0/lib/synvert/core/rewriter/instance.rb:101:in `block (2 levels) in process'
	from .../lib/ruby/gems/2.3.0/gems/synvert-core-0.14.0/lib/synvert/core/rewriter/instance.rb:140:in `process_with_node'
	from .../lib/ruby/gems/2.3.0/gems/synvert-core-0.14.0/lib/synvert/core/rewriter/instance.rb:99:in `block in process'
	from .../lib/ruby/gems/2.3.0/gems/synvert-core-0.14.0/lib/synvert/core/rewriter/instance.rb:90:in `each'
	from .../lib/ruby/gems/2.3.0/gems/synvert-core-0.14.0/lib/synvert/core/rewriter/instance.rb:90:in `process'
	from .../lib/ruby/gems/2.3.0/gems/synvert-core-0.14.0/lib/synvert/core/rewriter.rb:216:in `within_files'
	from (eval):9:in `block (2 levels) in load_rewriters'
	from .../lib/ruby/gems/2.3.0/gems/synvert-core-0.14.0/lib/synvert/core/rewriter.rb:154:in `instance_eval'
	from .../lib/ruby/gems/2.3.0/gems/synvert-core-0.14.0/lib/synvert/core/rewriter.rb:154:in `process'
	from .../lib/ruby/gems/2.3.0/gems/synvert-core-0.14.0/lib/synvert/core/rewriter.rb:82:in `call'
	from .../lib/ruby/gems/2.3.0/gems/synvert-0.9.0/lib/synvert/cli.rb:47:in `block in run'
	from .../lib/ruby/gems/2.3.0/gems/synvert-0.9.0/lib/synvert/cli.rb:44:in `each'
	from .../lib/ruby/gems/2.3.0/gems/synvert-0.9.0/lib/synvert/cli.rb:44:in `run'
	from .../lib/ruby/gems/2.3.0/gems/synvert-0.9.0/lib/synvert/cli.rb:12:in `run'
	from .../lib/ruby/gems/2.3.0/gems/synvert-0.9.0/bin/synvert:7:in `<top (required)>'
	from .../bin/synvert:22:in `load'
	from .../bin/synvert:22:in `<main>'
```

**Comment by flyerhzm** [comment]
@znz it's fixed now
